// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoleplaySwissArmyKnife.Services.StorageDetails;

namespace RoleplaySwissArmyKnife.Migrations
{
    [DbContext(typeof(StorageSQLiteContext))]
    partial class StorageSQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("RoleplaySwissArmyKnife.Models.ControlChannel", b =>
                {
                    b.Property<ulong>("ControlChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ResultChannelID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ControlChannelID");

                    b.ToTable("ControlChannels");
                });

            modelBuilder.Entity("RoleplaySwissArmyKnife.Models.InitiativeEntry", b =>
                {
                    b.Property<ulong>("InitiativeEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Initiative")
                        .HasColumnType("REAL");

                    b.Property<ulong>("InitiativeStateID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InitiativeEntryID");

                    b.HasIndex("InitiativeStateID");

                    b.ToTable("InitiativeEntries");
                });

            modelBuilder.Entity("RoleplaySwissArmyKnife.Models.InitiativeState", b =>
                {
                    b.Property<ulong>("InitiativeStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentInitiative")
                        .HasColumnType("REAL");

                    b.Property<bool>("InInitiative")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LastAnnounceMessageID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PinnedListMessageID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InitiativeStateID");

                    b.ToTable("InitiativeStates");
                });

            modelBuilder.Entity("RoleplaySwissArmyKnife.Models.ServerSettings", b =>
                {
                    b.Property<ulong>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandPrefix")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerID");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("RoleplaySwissArmyKnife.Models.InitiativeEntry", b =>
                {
                    b.HasOne("RoleplaySwissArmyKnife.Models.InitiativeState", "InitiativeState")
                        .WithMany("Characters")
                        .HasForeignKey("InitiativeStateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
